/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        bg: {
          sage: "#c1d3c9",
          sky: "#d8e6eb",
          pink: "#f6e5ed",
          yellow: "#fffdd1",
        },
        btn: {
          dark: "#0b0b0b",
        },
        "surface-container": "#edeeef",
        "on-primary-fixed": "#1c1b1b",
        "tertiary-fixed-dim": "#b7c9d5",
        "surface-container-high": "#e7e8e9",
        "on-secondary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "secondary-fixed-dim": "#d2c6a2",
        secondary: "#675e41",
        "on-tertiary-fixed-variant": "#384953",
        "on-secondary-container": "#6b6245",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#c8c6c5",
        "surface-dim": "#d9dadb",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#ecdfba",
        "on-surface": "#191c1d",
        "secondary-fixed": "#efe2bd",
        "on-primary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "primary-fixed": "#e5e2e1",
        "surface-container-highest": "#e1e3e4",
        surface: "#f8f9fa",
        "on-surface-variant": "#444748",
        "primary-fixed-dim": "#c8c6c5",
        "on-error": "#ffffff",
        "on-tertiary-container": "#758691",
        "surface-container-low": "#f3f4f5",
        "tertiary-container": "#0c1e26",
        background: "#f8f9fa",
        "on-secondary-fixed": "#211b05",
        error: "#ba1a1a",
        tertiary: "#000000",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#474746",
        outline: "#747878",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed-variant": "#4e462b",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed": "#0c1e26",
        "on-background": "#191c1d",
        "tertiary-fixed": "#d3e5f1",
        "on-error-container": "#93000a",
        primary: "#000000",
        "outline-variant": "#c4c7c7",
        "pastel-violet": "#F3E8FF",
        "pastel-emerald": "#D1FAE5",
        "pastel-amber": "#FEF3C7",
        "pastel-sky": "#E0F2FE",
        "pastel-rose": "#FFE4E6",
        "pastel-rose-dark": "#FDA4AF",
        "pastel-sky-dark": "#7DD3FC",
        "pastel-butter": "#FEF9C3",
        "pastel-butter-dark": "#FDE047"
      },
      borderRadius: {
        card: "28px",
      },
      spacing: {
        base: "8px",
        "card-gap": "20px",
        gutter: "16px",
        "container-padding": "24px",
        "section-margin": "40px",
      },
      fontFamily: {
        serif: ["Playfair Display", "Georgia", "serif"],
        sans: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        "label-lg": ["Lexend"],
        "headline-lg-mobile": ["Lexend"],
        "label-sm": ["Lexend"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "title-md": ["Lexend"],
        "headline-lg": ["Lexend"],
        "display-lg": ["Lexend"],
      },
      fontSize: {
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
