import { StyleSheet, Platform } from "react-native";
import Colors from "../constants/Colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 60,
    paddingHorizontal: 16,
    borderBottomWidth: 1.5,
    borderColor: "rgba(76, 59, 255, 0.1)",
    backgroundColor: Colors.surface,
  },
  profileButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(76, 59, 255, 0.08)",
  },
  headerTitle: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  menuButton: {
    width: 36,
    height: 36,
    justifyContent: "center",
    alignItems: "center",
  },
  menuLine: {
    width: 18,
    height: 2,
    backgroundColor: Colors.primary,
    borderRadius: 1,
    marginVertical: 2,
  },
  contentArea: {
    flex: 1,
  },
  // Bottom Navigation Layout
  bottomTabContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    height: 76,
    backgroundColor: Colors.surface,
    borderTopWidth: 1.5,
    borderColor: "rgba(76, 59, 255, 0.08)",
    paddingBottom: Platform.OS === "ios" ? 14 : 4,
  },
  tabButtonCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: "rgba(76, 59, 255, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.01)",
  },
  tabButtonCircleActive: {
    borderColor: Colors.primary,
    backgroundColor: "rgba(76, 59, 255, 0.1)",
  },
  tabButtonCapsule: {
    width: 76,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  tabButtonCapsuleActive: {
    backgroundColor: "#3125B3",
  },
  // Dashboard & Tab Content Layouts
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  card: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(76, 59, 255, 0.06)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTitle: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 6,
  },
  cardBalance: {
    color: Colors.text,
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  sectionTitle: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 14,
    letterSpacing: 0.5,
  },
  transactionList: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(76, 59, 255, 0.06)",
  },
  transactionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.03)",
  },
  transactionLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  transactionIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    backgroundColor: "rgba(76, 59, 255, 0.05)",
  },
  transactionDetails: {
    justifyContent: "center",
  },
  transactionTitle: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: "600",
  },
  transactionCategory: {
    color: Colors.textMuted,
    fontSize: 11,
    marginTop: 2,
  },
  transactionAmount: {
    fontSize: 14,
    fontWeight: "700",
  },
  incomeText: {
    color: "#00C853", // Standard green for income in light themes
  },
  expenseText: {
    color: Colors.error,
  },
  // Generic Tab Layout
  genericContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  genericTitle: {
    color: Colors.text,
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 10,
  },
  genericSubtitle: {
    color: Colors.textMuted,
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFill as object,
    backgroundColor: "rgba(0, 0, 0, 0.08)",
  },
  profileDropdownCard: {
    position: "absolute",
    top: 55,
    left: 12,
    width: 250,
    backgroundColor: Colors.surface,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.05)",
  },
  dropdownSectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text,
    marginTop: 6,
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 7,
  },
  premiumIcon: {
    width: 12,
    height: 12,
    borderRadius: 3,
    marginRight: 8,
  },
  premiumText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#D97706",
    flex: 1,
  },
  dropdownItemText: {
    fontSize: 13,
    color: Colors.textMuted,
    fontWeight: "500",
  },
  dropdownDivider: {
    height: 1,
    backgroundColor: "rgba(0, 0, 0, 0.06)",
    marginVertical: 8,
  },
  signOutText: {
    fontSize: 13,
    color: Colors.textMuted,
    fontWeight: "500",
  },
});

export default styles;
